// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtS42vOJrBfLUxGF5viQ4GJLXBvwaf-hU',
    appId: '1:21940943998:web:4c752c992d2ef5f4ffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    authDomain: 'mddprod-2954f.firebaseapp.com',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
    measurementId: 'G-PC7F73PN6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmj3qZ0jDGNgOkOSfQfaDg8_JY1RpidQc',
    appId: '1:21940943998:android:9f1aca5154856db5ffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMlLpbssXzm_3HZLatACPvuH74hrkVk6U',
    appId: '1:21940943998:ios:1c72070c398f81e5ffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
    iosBundleId: 'com.example.mdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMlLpbssXzm_3HZLatACPvuH74hrkVk6U',
    appId: '1:21940943998:ios:1c72070c398f81e5ffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
    iosBundleId: 'com.example.mdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtS42vOJrBfLUxGF5viQ4GJLXBvwaf-hU',
    appId: '1:21940943998:web:4c752c992d2ef5f4ffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    authDomain: 'mddprod-2954f.firebaseapp.com',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
    measurementId: 'G-PC7F73PN6E',
  );
}
